name: Notify Commit
on:
  push:
    branches:
      - main
jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Samuel L. Jackson
        uses: lob/action_sam_jackson@0.0.2
        with:
          message: 'Hello dear human being'
          token: ${{secrets.GITHUB_TOKEN}}
