name: Notify Commit
on:
  push:
    branches:
      - main
jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Send Email
        run: |
          echo "A commit has been made to the main branch." | mail -s "Commit Notification" enesyildizmr@gmail.com
